name: anonymous_chat
description: A new Flutter project.


# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

  firebase_core: ^1.8.0
  cloud_firestore: ^3.2.1
  firebase_auth: ^3.1.4
  firebase_messaging: ^11.4.4

  algolia: ^1.1.1
  flutter_riverpod: ^1.0.4
  flutter_dotenv: ^5.0.2
  sqflite: ^2.0.0+4
  shared_preferences: ^2.0.8
  path_provider: ^2.0.6
  app_settings: ^4.1.8
  tuple: ^2.0.0
  connectivity_plus: ^2.0.2
  url_launcher: ^6.0.12

  observable_ish: ^4.0.6

  flutter_spinkit: ^5.1.0
  in_app_review: ^2.0.3
  fluttericon: ^2.0.0
  flutter_slidable: ^1.3.0
  pin_code_fields: ^7.3.0
  implicitly_animated_reorderable_list: ^0.4.2
  bubble: ^1.2.1
  flutter_staggered_animations: ^1.0.0
  
  sqlite_viewer: ^1.0.5
  
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  flutter_native_splash: ^2.2.3+1

dev_dependencies:

  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/icons/
    - assets/
  
  fonts:
    - family: SourceSans
      fonts:
      - asset: assets/fonts/SourceSansPro-Bold.ttf
        weight: 700
      - asset: assets/fonts/SourceSansPro-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/SourceSansPro-Regular.ttf
        weight: 400
      - asset: assets/fonts/SourceSansPro-Light.ttf
        weight: 300
    
    - family: Playfair
      fonts:
      - asset: assets/fonts/PlayfairDisplay-Bold.ttf
        weight: 700
      - asset: assets/fonts/PlayfairDisplay-Medium.ttf
        weight: 500
      - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        weight: 400

## Configuration for the splash screen.
flutter_native_splash:
    color: "#000000"
    image: assets/icons/splash.png